### PR TITLE
Validate Uploaded files by default

### PR DESCRIPTION
**Pull request by crlcu**
Hi there,

This request is added in order to fix issues for uploaded files validation.

### CODE REVIEW

**Comment by jontaylor** [comment]
Battle tested in production, looks good.

**Comment by crlcu** [comment]
Hey mate,
Could you please have a look at this pull request.

Thanks.

**Comment by crlcu** [comment]
Any updates on this?

**Comment by koorchik** [comment]
Just uploaded the new version to CPAN. Please, let me know if there will any issues with it.

**Comment by koorchik** [comment]
Please, take a look at - https://metacpan.org/pod/Validator::LIVR. This validator was inspired by Validate::Tiny.
Here are the ideas behind the LIVR - http://blog.webbylab.com/language-independent-validation-rules-library/

The only thing, that there is no LIVR plugin for Mojolicious yet. But it will be cool if someone will do it)

**Pull request merged**
